# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x4vqHKtckvyeFSiwE28b6LdJPONuTuD6
"""

import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split

#=================================
# 1.Load Dataset
#=================================
# Read the housing dataset from csv file
# and store it in a pandas dataframe
df = pd.read_csv("/content/hotel_bookings.csv")
#Display the first 5 rows to check the dataset
print(df.head())

print(df.columns.tolist())

#================================
# 2. Select inputs and targets
#================================

# Select the columns that will be given
# as inputs to the neural network
x = df[[
    "lead_time",
    "adr"
]]

# Select the value that the ANN needs to predict
y = df["is_canceled"]

#===============================
# 3. Train/Test Split
#===============================
# Divide the data into training and testing sets
# 80% is used for training and 20% for testing
x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

#=================================
# 4. convert to pytorch tensors
#=================================
# convert the training input data into pytorch tensor
#pytorch tensors for use by the ANN.
x_train = torch.tensor(
    x_train.values,
    dtype=torch.float32
)
# convert the testing input data into tensors.
x_test = torch.tensor(
    x_test.values,
    dtype=torch.float32
)
# convert training target values into tensors
# reshape() changes the data into required shape.
y_train = torch.tensor(
    y_train.values,
    dtype=torch.float32
).reshape(-1,1)
# convert testing target values into tensors.
y_test = torch.tensor(
    y_test.values,
    dtype=torch.float32
).reshape(-1,1)

#================================
# 5. Create ANN
#================================
# create a neural network class for predicting hotel booking cancellation.
class HotelBookingANN(nn.Module):
    def __init__(self):
      # Initialize the parent neural network class.
        super().__init__()
        # First layer:2 input features and 16 neurons.
        self.layer1 = nn.Linear(2, 16)
        #second layer :16 neurons connected to 8 neurons.
        self.layer2 = nn.Linear(16, 8)
        #output layer:8 neurons produce 1 output.
        self.output = nn.Linear(8, 1)
    def forward(self, x):
      #pass input through the first layer
      #and apply the relu activation function
      x = torch.relu(self.layer1(x))
      #pass the result through the second layer and apply relu again.
      x = torch.relu(self.layer2(x))
      #pass the result to the output layer
      #to get the predicted booking cancellation.
      x = self.output(x)
      return x
#create an object of the ANN class.
model = HotelBookingANN()
#display the structure of neural network.
print(model)

#============================
# 6. Loss function
#============================

loss_function = nn.BCEWithLogitsLoss()

# BCEWithLogitsLoss is used for binary classification.
# It measures the error between predicted cancellation
# and the actual cancellation (0 or 1).

#============================
# 7. Optimizer
#============================
# Adam optimizer adjusts the network weights to reduce the prediction error.
optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

#============================
# 8. Training
#============================
# The ANN will learn from the training data
# for 1000 complete training rounds.
epochs = 1000

for epoch in range(epochs):

    # Give the training data to the ANN
    # and get the predicted cancellation values.
    prediction = model(x_train)

    # Compare predictions with actual values
    # and calculate the prediction error.
    loss = loss_function(prediction, y_train)

    # Clear the gradients from the previous step.
    optimizer.zero_grad()

    # Calculate gradients using backpropagation
    # so the ANN can learn from its error.
    loss.backward()

    # Update the weights of the ANN.
    optimizer.step()

    # Display the loss after every 100 epochs.
    if (epoch + 1) % 100 == 0:
        print(
            f"Epoch: {epoch+1}/{epochs} "
            f"Loss: {loss.item():.2f}"
        )

#============================
# 9. Testing
#============================

# Turn off gradient calculation because we are only testing.
with torch.no_grad():

    # Get predictions from the test data.
    prediction = model(x_test)

    # Convert model output into 0 or 1.
    predicted_class = (torch.sigmoid(prediction) >= 0.5).float()

    # Calculate accuracy.
    accuracy = (predicted_class == y_test).float().mean()

print("Test Accuracy:", accuracy.item() * 100, "%")
